// Bundles web/app.tsx (slides, Player and fonts) and inlines it into
// web/index.html: one self-contained page that opens by double-click.
// Also writes out/artifact.html, the same page without the document
// skeleton, for publishing as a claude.ai artifact.
//
//   npm run build-web
import { build } from "esbuild";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

const root = new URL("../", import.meta.url);
const result = await build({
  entryPoints: [new URL("web/app.tsx", root).pathname],
  bundle: true,
  minify: true,
  format: "iife",
  platform: "browser",
  target: "es2020",
  jsx: "automatic",
  define: { "process.env.NODE_ENV": '"production"' },
  loader: { ".woff2": "dataurl" },
  legalComments: "none",
  write: false,
});
const js = result.outputFiles[0].text.replace(/<\/script/gi, "<\\/script");
const page = readFileSync(new URL("web/page.html", root), "utf8");
const body = `${page}<script>${js}</script>\n`;
// in the standalone page the title and styles belong in <head>
const split = page.indexOf('<div id="root">');
const head = page.slice(0, split);
const rest = `${page.slice(split)}<script>${js}</script>\n`;

writeFileSync(
  new URL("web/index.html", root),
  `<!doctype html>\n<!-- Generated by tools/build-web.mjs from web/page.html and web/app.tsx. Do not edit. -->\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n${head}</head>\n<body>\n${rest}</body>\n</html>\n`,
);
mkdirSync(new URL("out/", root), { recursive: true });
writeFileSync(new URL("out/artifact.html", root), body);
console.log(`web/index.html ${(Buffer.byteLength(body) / 1024).toFixed(0)} KB`);
