// Writes src/ireland.ts: the island of Ireland (Republic + Northern Ireland)
// as an SVG path, from Natural Earth 1:10m via world-atlas, plus the
// Mercator parameters src/geo.ts uses to place sites on the same map.
//
//   npm run coastline
import { readFileSync, writeFileSync } from "node:fs";
import { feature } from "topojson-client";
import { geoMercator, geoPath } from "d3-geo";

const topo = JSON.parse(readFileSync(new URL("../node_modules/world-atlas/countries-10m.json", import.meta.url)));
const countries = feature(topo, topo.objects.countries).features;
const polys = [];
for (const f of countries) {
  if (!["372", "826"].includes(f.id)) continue;
  const list = f.geometry.type === "Polygon" ? [f.geometry.coordinates] : f.geometry.coordinates;
  for (const p of list) {
    const [lon, lat] = p[0][0];
    // the island of Ireland: all of the Republic, and the UK polygon west of 5.4°W
    if (f.id === "826" && !(lon < -5.3 && lat > 53.9 && lat < 55.5)) continue;
    polys.push(p);
  }
}
const island = { type: "Feature", geometry: { type: "MultiPolygon", coordinates: polys } };

const W = 700, H = 900;
const projection = geoMercator().fitExtent([[20, 20], [W - 20, H - 20]], island);
const path = geoPath(projection);

// keep pieces bigger than a few pixels, and drop points closer than 1.2px
let d = "";
for (const p of polys) {
  const f = { type: "Feature", geometry: { type: "Polygon", coordinates: p } };
  if (path.area(f) < 6) continue;
  const ring = p[0].map((c) => projection(c));
  const kept = [ring[0]];
  for (const pt of ring.slice(1)) {
    const last = kept[kept.length - 1];
    if (Math.hypot(pt[0] - last[0], pt[1] - last[1]) >= 1.2) kept.push(pt);
  }
  if (kept.length < 4) continue;
  d += "M" + kept.map(([x, y]) => `${x.toFixed(1)} ${y.toFixed(1)}`).join("L") + "Z";
}
const [tx, ty] = projection.translate();
const out = `// Generated by tools/coastline.mjs from Natural Earth 1:10m (world-atlas). Do not edit.
export const MAP_W = ${W};
export const MAP_H = ${H};
/** d3 geoMercator scale and translate that fit the island into MAP_W × MAP_H */
export const MERCATOR = { scale: ${projection.scale()}, tx: ${tx}, ty: ${ty} };
export const IRELAND_PATH =
  "${d}";
`;
writeFileSync(new URL("../src/ireland.ts", import.meta.url), out);
console.log("path bytes", d.length, "pieces", (d.match(/M/g) || []).length);
