// What each part is made of, from materials available in Neolithic Ireland (c. 3800–3200 BC).
// `parts` are the model's part ids; `evidence` says whether the material itself is attested for the
// period (DOCUMENTED) or only proposed (HYPOTHETICAL). Every acoustic use here is hypothetical.

export const MATERIALS = [
  {
    id: "capstone",
    parts: ["capstone"],
    name: "Capstone",
    material: "One slab of local bedrock or a glacial erratic",
    source: "The nearest suitable outcrop or boulder: granophyre and granite around Slieve Gullion, sandstone or limestone elsewhere. Levered on timber rollers and earth ramps.",
    quantity: "About 3.4 × 2.4 × 0.6 m, roughly 10 t",
    evidence: "DOCUMENTED",
  },
  {
    id: "orthostats",
    parts: ["portal-stones", "side-stones", "backstone", "doorstone"],
    name: "Portal stones, side stones, backstone, doorstone",
    material: "Upright slabs of the same local stone, set in packed sockets",
    source: "Split along natural bedding with wedges and levers; trimmed with stone hammers.",
    quantity: "Seven uprights, about 1–3 t each",
    evidence: "DOCUMENTED",
  },
  {
    id: "cairn",
    parts: ["cairn", "kerb"],
    name: "Cairn and kerb",
    material: "Field stones, earth and turf sods over the chamber; a kerb of larger boulders",
    source: "Cleared from the surrounding fields as they were farmed.",
    quantity: "About 150 m³, some 200–250 t",
    evidence: "DOCUMENTED",
  },
  {
    id: "packing",
    parts: ["packing", "collar"],
    name: "Portal packing and throat collar",
    material: "Dry-stone walling and turf in the portal gap, leaving a 0.3 m throat; a carved alder ring sealed with clay",
    source: "Stone from the cairn; alder from wet ground nearby, carved green.",
    quantity: "About 0.4 m³ of packing; one ring",
    evidence: "HYPOTHETICAL",
  },
  {
    id: "frame",
    parts: ["staves", "hoops"],
    name: "Collector frame",
    material: "Sixteen split hazel or ash staves on seven bent ash hoops, lashed with rawhide or willow",
    source: "Coppiced hazel and ash; green ash bends well. Wattle-working is known from the period.",
    quantity: "About 35 m of staves and 20 m of hoop, 12–15 kg",
    evidence: "HYPOTHETICAL",
  },
  {
    id: "skin",
    parts: ["skin"],
    name: "Collector skin",
    material: "Cattle hide sewn over the frame, or overlapped birch-bark sheets",
    source: "Cattle arrived with farming around 3800 BC; birch grew on poorer and upland ground.",
    quantity: "About 5.5 m²: two or three hides",
    evidence: "HYPOTHETICAL",
  },
  {
    id: "sealant",
    parts: ["skin", "collar"],
    name: "Seams and joints",
    material: "Birch-bark tar, with pine resin or hide glue",
    source: "Birch-bark tar is a well-attested Neolithic adhesive in Europe.",
    quantity: "Under 1 kg",
    evidence: "DOCUMENTED",
  },
  {
    id: "trestles",
    parts: ["trestles"],
    name: "Trestles",
    material: "Two oak or ash A-frames with a cradle, so the collector can be turned toward a neighbour",
    source: "Split oak and ash poles; oak planking is known from Neolithic Irish houses.",
    quantity: "Six poles of about 2 m",
    evidence: "HYPOTHETICAL",
  },
  {
    id: "lining",
    parts: ["lining"],
    name: "Chamber lining",
    material: "Bracken and heather bedding, fleeces and hides on the floor and lower walls",
    source: "Cut locally; sheep arrived with farming.",
    quantity: "About 10 m², bringing reverberation down from about 2.3 s to about 0.2 s",
    evidence: "HYPOTHETICAL",
  },
  {
    id: "tools",
    parts: [],
    name: "Tools",
    material: "Polished stone axes, flint blades, antler picks, timber levers and hide ropes",
    source: "Porcellanite axes from Tievebulliagh and Rathlin Island, and Antrim flint, travelled across Neolithic Ireland.",
    quantity: "",
    evidence: "DOCUMENTED",
  },
];
