// Bundles src/dashboard.js and inlines it into index.html, loading three.js from jsdelivr
// through an import map. Also writes out/artifact.html (the page without its document
// skeleton, for claude.ai) and out/test.html (three.js from node_modules, for a local server).
//
//   npm run build
import { build } from "esbuild";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

const root = new URL("../", import.meta.url);
const THREE_VERSION = JSON.parse(readFileSync(new URL("node_modules/three/package.json", root))).version;
const result = await build({
  entryPoints: [new URL("src/dashboard.js", root).pathname],
  bundle: true,
  minify: true,
  format: "esm",
  platform: "browser",
  target: "es2020",
  external: ["three", "three/addons/*"],
  legalComments: "none",
  write: false,
});
const js = result.outputFiles[0].text.replace(/<\/script/gi, "<\\/script");
const page = readFileSync(new URL("page.html", root), "utf8");
const importmap = (base) =>
  `<script type="importmap">${JSON.stringify({ imports: { three: `${base}build/three.module.js`, "three/addons/": `${base}examples/jsm/` } })}</script>\n`;
const cdn = `https://cdn.jsdelivr.net/npm/three@${THREE_VERSION}/`;
const body = (base) => `${page}\n${importmap(base)}<script type="module">${js}</script>\n`;

const split = page.indexOf('<div class="sheet">');
const doc = (base) =>
  `<!doctype html>\n<!-- Generated by tools/build.mjs from page.html and src/. Do not edit. -->\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n${page.slice(0, split)}${importmap(base)}</head>\n<body>\n${page.slice(split)}\n<script type="module">${js}</script>\n</body>\n</html>\n`;

writeFileSync(new URL("index.html", root), doc(cdn));
mkdirSync(new URL("out/", root), { recursive: true });
writeFileSync(new URL("out/artifact.html", root), body(cdn));
writeFileSync(new URL("out/test.html", root), doc("/node_modules/three/"));
console.log(`index.html ${(Buffer.byteLength(doc(cdn)) / 1024).toFixed(0)} KB, three.js ${THREE_VERSION} from jsdelivr`);
